"""
Package rawspec_testing

Creates/recreates the rawspec testing trial directory.

* Create <trial directory>.
* cd <trial diretcory>
* For each .raw file in the <baseline directory>, do the following:
    - rawspec   <rawspec options>  --dest .   <full path of the .raw file prefix>
* For each ext = .fil or .h5 file in the <trial directory> produced by rawspec, do the following:
    - Optionally, turboSETI   -s 10   -g y   -d <GPU_ID>   <0000.ext file>
    - Create a .tbldat file.
    - Create a .tblhdr file.
    - Create a .tbldsel file.
* rawspectest stdout --> <.tblnpols file>
* Cleanup: rm *.fil, *.h5, *.dat, *.log
"""

MY_NAME = "runner"

import sys
import os
import glob
import time
import shutil
import stat
from datetime import timedelta
from argparse import ArgumentParser

# Helper functions:
from site_parameters import BASELINE_DIR, RAWSPEC_OPTS, RAWSPECTEST_TBL, \
                            RUN_TURBO_SETI, SELECTED, TESTING_NODE, TRIAL_DIR
from common import MY_VERSION, TS_SNR_THRESHOLD, oops, run_cmd, logger
import dat2tbl
import hdr2tbl
import npols2tbl
import dsel2tbl


def main(args=None):
    """
    Parameters
    ----------
    args : Namespace
        Command-line parameters. The default is None.

    Returns
    -------
    None.

    """

    # Create an option parser to get command-line input/arguments
    parser = ArgumentParser(description="installer version {}."
                                        .format(MY_VERSION))
    parser.add_argument("-g", "--gpu_id",
                        dest="gpu_id",
                        type=int,
                        required=True,
                        help="GPU device ID (0-3) to use in rawspec and turbo_seti")
    parser.add_argument("--fbh5",
                        dest="flag_fbh5",
                        default=False,
                        action="store_true",
                        help="Rawspec will produce .h5 files instead of .fil files.")
    parser.add_argument("-S", "--skip_cleanup",
                        dest="flag_skip_cleanup",
                        default=True,
                        action="store_true",
                        help="Skip removing the files generated by rawspec and turbo_seti after the tables are produced.")
    parser.add_argument("-v", "--version",
                        dest="show_version",
                        default=False,
                        action="store_true",
                        help="Flag: Show the installer version and exit")

    # Validate arguments.
    if args is None:
        args = parser.parse_args()
    else:
        args = parser.parse_args(args)

    if args.show_version:
        print("runner: {}".format(MY_VERSION))
        sys.exit(0)

    # Process --fbh5 option.
    if args.flag_fbh5:
        fbh5_opt = "--fbh5"
        fileext = ".h5"
        logger(MY_NAME, "Output format is FBH5.")
    else:
        fbh5_opt = ""
        fileext = ".fil"
        logger(MY_NAME, "Output format is SIGPROC Filterbank.")

    # Show system information.
    osinfo = os.uname()
    logger(MY_NAME, "O/S name = {}, release = {}, version = {}"
                .format(osinfo.sysname, osinfo.release, osinfo.version))
    logger(MY_NAME, "Node name = {}, CPU type = {}, HOME = {}"
                .format(osinfo.nodename, osinfo.machine, os.environ["HOME"]))
    if TESTING_NODE != "any":
        if osinfo.nodename != TESTING_NODE:
            oops("Node name must be {}".format(TESTING_NODE))

    # Take a timestamp
    time1 = time.time()

    # TRIAL_DIR still exist?  If so, remove it.
    if os.path.exists(TRIAL_DIR): # Yes, it exists.
        try:
            shutil.rmtree(TRIAL_DIR, ignore_errors=True)
        except:
            oops("shutil.rmtree({}) FAILED !!".format(TRIAL_DIR))

    # Create TRIAL_DIR.
    try:
        os.mkdir(TRIAL_DIR)
        mode = stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO
        os.chmod(TRIAL_DIR, mode=mode)
        logger(MY_NAME, "Created directory {} with mode={}."
              .format(TRIAL_DIR, oct(mode)))
    except:
        oops("os.mkdir/os.chmod({}, mode={}) FAILED !!"
             .format(TRIAL_DIR, oct(mode)))

    # Go to TRIAL_DIR.
    try:
        os.chdir(TRIAL_DIR)
    except:
        oops("os.chdir({}) FAILED !!".format(TRIAL_DIR))

    # For each unique file stem, run rawspec.
    # Note: If a rawspec file is X.0000.raw then its rawstem is X.
    for ii, rawstem in enumerate(SELECTED):
        rawspec_opts = RAWSPEC_OPTS[ii]
        cmd = "rawspec  {}  {}  -g {}  -d .  {}/{}".format(rawspec_opts, fbh5_opt, args.gpu_id, BASELINE_DIR, rawstem)
        run_cmd(cmd, logger)

    # For each unique 0000.fil, run turbo_seti, dat2tbl, and hdr2tbl.
    for fb_file in sorted(glob.glob("*{}".format(fileext))):
        if RUN_TURBO_SETI:
            cmd = "turboSETI  --snr {}  --gpu y  --gpu_id {}  --n_coarse_chan 64  {}" \
                  .format(TS_SNR_THRESHOLD, args.gpu_id, fb_file)
            run_cmd(cmd, logger)
            dat_name = fb_file.split("/")[-1].replace(fileext, ".dat")
            tbldat_name = fb_file.split("/")[-1].replace(fileext, '.tbldat')
            try:
                dat2tbl.main([dat_name, tbldat_name])
            except:
                oops("dat2tbl.main({}, {}) FAILED !!".format(dat_name, tbldat_name))
        tblhdr_name = fb_file.split("/")[-1].replace(fileext, ".tblhdr")
        try:
            hdr2tbl.main([fb_file, tblhdr_name])
        except:
            oops("hdr2tbl.main({}, {}) FAILED !!".format(fb_file, tblhdr_name))
        tbldsel_name = fb_file.split('/')[-1].replace(fileext, ".tbldsel")
        try:
            dsel2tbl.main([fb_file, tbldsel_name])
        except:
            oops("dsel2tbl.main({}, {}) FAILED !!".format(fb_file, tbldsel_name))

        logger(MY_NAME, "Created tables for {}.".format(fb_file))

    # rawspectest cases.
    tblnpols_name = TRIAL_DIR + RAWSPECTEST_TBL
    npols2tbl.main([tblnpols_name])

    # Do post-run cleanup.
    if args.flag_skip_cleanup:
        logger(MY_NAME, "Skipping post-run cleanup.")
    else:
        cmd = "rm *.dat *.fil *.h5 *.log"
        run_cmd(cmd, ignore_errors=True)

    # Bye-bye.
    time2 = time.time()
    time_delta = timedelta(seconds=(time2 - time1))
    logger(MY_NAME, "Bye-bye, elapsed hh:mm:ss = {}".format(time_delta))


if __name__ == "__main__":
    main()
